# Generated by Django 4.2 on 2023-04-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_rename_created_date_comment_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
